import type { Template, TemplateCategory, TemplatePack } from '../types'

export const TEMPLATE_CATEGORIES: TemplateCategory[] = [
  { id: 'portrait',   name: 'Portrait',         emoji: '🧑‍🎨', gradient: 'from-violet-500 to-purple-600',   description: 'Professional headshots & portraits' },
  { id: 'instagram',  name: 'Instagram',         emoji: '📸', gradient: 'from-pink-500 to-rose-500',        description: 'Square posts, stories & reels' },
  { id: 'youtube',    name: 'YouTube',           emoji: '▶️',  gradient: 'from-red-500 to-orange-500',       description: 'Thumbnails that get clicks' },
  { id: 'logo',       name: 'Logo',              emoji: '✨', gradient: 'from-amber-400 to-yellow-500',     description: 'Brand marks & identity' },
  { id: 'passport',   name: 'Passport',          emoji: '🛂', gradient: 'from-blue-500 to-cyan-500',        description: 'Official ID & visa photos' },
  { id: 'product',    name: 'Product',           emoji: '🛍️', gradient: 'from-emerald-400 to-teal-500',    description: 'E-commerce & lifestyle shots' },
  { id: 'poster',     name: 'Poster',            emoji: '🎬', gradient: 'from-indigo-500 to-violet-500',    description: 'Events, movies & concerts' },
  { id: 'banner',     name: 'Banner',            emoji: '🏳️', gradient: 'from-cyan-400 to-blue-500',       description: 'Headers & web banners' },
  { id: 'wallpaper',  name: 'Wallpaper',         emoji: '🖼️', gradient: 'from-fuchsia-500 to-pink-500',   description: 'Phone & desktop wallpapers' },
  { id: 'festival',   name: 'Festival',          emoji: '🎉', gradient: 'from-orange-400 to-rose-500',      description: 'Holiday & celebration designs' },
]

export const TEMPLATES: Template[] = [
  // ── Portrait ────────────────────────────────────────────────────────────────
  {
    id: 'portrait-headshot',
    name: 'Professional Headshot',
    category: 'portrait',
    width: 800, height: 1000,
    description: '4:5 ratio — LinkedIn & corporate profiles',
    gradient: 'from-violet-600 to-purple-700',
    accentColor: '#8b5cf6',
    tags: ['linkedin', 'corporate', 'headshot'],
  },
  {
    id: 'portrait-artistic',
    name: 'Artistic Portrait',
    category: 'portrait',
    width: 1080, height: 1350,
    description: '4:5 — Instagram portrait with artistic framing',
    gradient: 'from-fuchsia-500 to-violet-600',
    accentColor: '#d946ef',
    tags: ['artistic', 'instagram', 'creative'],
    isPremium: true,
  },
  {
    id: 'portrait-editorial',
    name: 'Editorial Portrait',
    category: 'portrait',
    width: 800, height: 1200,
    description: '2:3 — Magazine & editorial style',
    gradient: 'from-slate-700 to-violet-600',
    accentColor: '#6366f1',
    tags: ['editorial', 'magazine', 'fashion'],
    isPremium: true,
  },
  {
    id: 'portrait-square',
    name: 'Square Headshot',
    category: 'portrait',
    width: 800, height: 800,
    description: '1:1 — Social media profile picture',
    gradient: 'from-blue-500 to-violet-500',
    accentColor: '#3b82f6',
    tags: ['profile', 'social', 'square'],
  },

  // ── Instagram ───────────────────────────────────────────────────────────────
  {
    id: 'instagram-square',
    name: 'Square Post',
    category: 'instagram',
    width: 1080, height: 1080,
    description: '1:1 — Classic Instagram feed post',
    gradient: 'from-pink-500 to-rose-500',
    accentColor: '#f43f5e',
    tags: ['feed', 'post', 'social'],
  },
  {
    id: 'instagram-portrait',
    name: 'Portrait Post',
    category: 'instagram',
    width: 1080, height: 1350,
    description: '4:5 — Maximum feed real-estate',
    gradient: 'from-rose-500 to-pink-600',
    accentColor: '#ec4899',
    tags: ['feed', 'portrait', 'tall'],
  },
  {
    id: 'instagram-story',
    name: 'Story & Reel',
    category: 'instagram',
    width: 1080, height: 1920,
    description: '9:16 — Full-screen story & reel',
    gradient: 'from-fuchsia-500 to-rose-500',
    accentColor: '#d946ef',
    tags: ['story', 'reel', 'vertical'],
  },
  {
    id: 'instagram-carousel',
    name: 'Carousel Slide',
    category: 'instagram',
    width: 1080, height: 1080,
    description: '1:1 — Swipeable carousel template',
    gradient: 'from-violet-500 to-pink-500',
    accentColor: '#8b5cf6',
    tags: ['carousel', 'multi-slide'],
    isPremium: true,
  },

  // ── YouTube ─────────────────────────────────────────────────────────────────
  {
    id: 'youtube-thumbnail',
    name: 'Standard Thumbnail',
    category: 'youtube',
    width: 1280, height: 720,
    description: '16:9 — The classic YouTube thumbnail',
    gradient: 'from-red-500 to-orange-500',
    accentColor: '#ef4444',
    tags: ['thumbnail', 'video', 'youtube'],
  },
  {
    id: 'youtube-gaming',
    name: 'Gaming Thumbnail',
    category: 'youtube',
    width: 1280, height: 720,
    description: '16:9 — High-energy gaming style',
    gradient: 'from-red-600 to-purple-600',
    accentColor: '#dc2626',
    tags: ['gaming', 'esports', 'bold'],
    isPremium: true,
  },
  {
    id: 'youtube-tutorial',
    name: 'Tutorial & How-To',
    category: 'youtube',
    width: 1280, height: 720,
    description: '16:9 — Clean, informative layout',
    gradient: 'from-orange-500 to-amber-500',
    accentColor: '#f97316',
    tags: ['tutorial', 'howto', 'education'],
  },
  {
    id: 'youtube-shorts',
    name: 'YouTube Shorts',
    category: 'youtube',
    width: 1080, height: 1920,
    description: '9:16 — Vertical short-form content',
    gradient: 'from-red-500 to-rose-600',
    accentColor: '#ef4444',
    tags: ['shorts', 'vertical', 'short-form'],
  },

  // ── Logo ────────────────────────────────────────────────────────────────────
  {
    id: 'logo-modern',
    name: 'Modern Logo',
    category: 'logo',
    width: 500, height: 500,
    description: '1:1 — Clean minimal brand mark',
    gradient: 'from-amber-400 to-yellow-500',
    accentColor: '#f59e0b',
    tags: ['modern', 'minimal', 'brand'],
  },
  {
    id: 'logo-circle',
    name: 'Circle Badge',
    category: 'logo',
    width: 500, height: 500,
    description: '1:1 — Circular badge & emblem',
    gradient: 'from-yellow-400 to-orange-500',
    accentColor: '#eab308',
    tags: ['badge', 'circle', 'emblem'],
  },
  {
    id: 'logo-transparent',
    name: 'Transparent Logo',
    category: 'logo',
    width: 500, height: 500,
    description: '1:1 — PNG with transparent background',
    gradient: 'from-amber-500 to-amber-700',
    accentColor: '#d97706',
    tags: ['transparent', 'png', 'watermark'],
    isPremium: true,
  },

  // ── Passport ────────────────────────────────────────────────────────────────
  {
    id: 'passport-standard',
    name: 'Standard Passport',
    category: 'passport',
    width: 413, height: 531,
    description: '35×45mm — International standard',
    gradient: 'from-blue-600 to-cyan-500',
    accentColor: '#2563eb',
    tags: ['passport', 'id', 'official'],
  },
  {
    id: 'passport-us',
    name: 'US Passport',
    category: 'passport',
    width: 600, height: 600,
    description: '2×2 inch — US passport & visa',
    gradient: 'from-blue-500 to-blue-700',
    accentColor: '#1d4ed8',
    tags: ['us', 'visa', 'american'],
  },
  {
    id: 'passport-id-card',
    name: 'ID Card Photo',
    category: 'passport',
    width: 480, height: 640,
    description: '3:4 — National ID & driver\'s license',
    gradient: 'from-cyan-500 to-blue-600',
    accentColor: '#0891b2',
    tags: ['id', 'card', 'license'],
  },

  // ── Product ─────────────────────────────────────────────────────────────────
  {
    id: 'product-square',
    name: 'Product Square',
    category: 'product',
    width: 1000, height: 1000,
    description: '1:1 — Amazon & Shopify listing',
    gradient: 'from-emerald-400 to-teal-500',
    accentColor: '#10b981',
    tags: ['ecommerce', 'amazon', 'shopify'],
  },
  {
    id: 'product-landscape',
    name: 'Product Landscape',
    category: 'product',
    width: 1200, height: 900,
    description: '4:3 — Website & banner use',
    gradient: 'from-teal-400 to-emerald-500',
    accentColor: '#14b8a6',
    tags: ['website', 'banner', 'landscape'],
  },
  {
    id: 'product-flatlay',
    name: 'Flat Lay',
    category: 'product',
    width: 1080, height: 1080,
    description: '1:1 — Styled overhead flat lay',
    gradient: 'from-emerald-500 to-cyan-500',
    accentColor: '#059669',
    tags: ['flatlay', 'overhead', 'styled'],
    isPremium: true,
  },
  {
    id: 'product-white',
    name: 'White Background',
    category: 'product',
    width: 1000, height: 1000,
    description: '1:1 — Clean white product shot',
    gradient: 'from-slate-300 to-slate-400',
    accentColor: '#64748b',
    tags: ['white', 'clean', 'minimal'],
  },

  // ── Poster ──────────────────────────────────────────────────────────────────
  {
    id: 'poster-event',
    name: 'Event Poster',
    category: 'poster',
    width: 600, height: 900,
    description: '2:3 — Concert & event announcement',
    gradient: 'from-indigo-600 to-violet-600',
    accentColor: '#4f46e5',
    tags: ['event', 'concert', 'announcement'],
  },
  {
    id: 'poster-movie',
    name: 'Movie Poster',
    category: 'poster',
    width: 675, height: 1000,
    description: '27×40 — Cinematic movie poster',
    gradient: 'from-slate-800 to-indigo-600',
    accentColor: '#6366f1',
    tags: ['movie', 'cinema', 'film'],
    isPremium: true,
  },
  {
    id: 'poster-a4',
    name: 'A4 Flyer',
    category: 'poster',
    width: 595, height: 842,
    description: 'A4 — Print-ready flyer & brochure',
    gradient: 'from-violet-500 to-indigo-600',
    accentColor: '#7c3aed',
    tags: ['a4', 'print', 'flyer'],
  },

  // ── Banner ──────────────────────────────────────────────────────────────────
  {
    id: 'banner-facebook',
    name: 'Facebook Cover',
    category: 'banner',
    width: 820, height: 312,
    description: '820×312 — Facebook page cover',
    gradient: 'from-blue-500 to-cyan-500',
    accentColor: '#3b82f6',
    tags: ['facebook', 'cover', 'social'],
  },
  {
    id: 'banner-twitter',
    name: 'Twitter Header',
    category: 'banner',
    width: 1500, height: 500,
    description: '1500×500 — Twitter/X profile header',
    gradient: 'from-sky-400 to-cyan-500',
    accentColor: '#0ea5e9',
    tags: ['twitter', 'x', 'header'],
  },
  {
    id: 'banner-linkedin',
    name: 'LinkedIn Banner',
    category: 'banner',
    width: 1584, height: 396,
    description: '1584×396 — Professional LinkedIn cover',
    gradient: 'from-blue-600 to-blue-700',
    accentColor: '#1d4ed8',
    tags: ['linkedin', 'professional', 'cover'],
    isPremium: true,
  },
  {
    id: 'banner-youtube-art',
    name: 'YouTube Channel Art',
    category: 'banner',
    width: 2560, height: 1440,
    description: '2560×1440 — YouTube channel banner',
    gradient: 'from-red-500 to-orange-600',
    accentColor: '#ef4444',
    tags: ['youtube', 'channel', 'art'],
  },

  // ── Wallpaper ────────────────────────────────────────────────────────────────
  {
    id: 'wallpaper-phone',
    name: 'Phone Wallpaper',
    category: 'wallpaper',
    width: 1080, height: 1920,
    description: '9:16 — Android & iPhone home screen',
    gradient: 'from-fuchsia-600 to-violet-700',
    accentColor: '#c026d3',
    tags: ['phone', 'mobile', 'home-screen'],
  },
  {
    id: 'wallpaper-lock',
    name: 'Lock Screen',
    category: 'wallpaper',
    width: 1080, height: 1920,
    description: '9:16 — Phone lock screen art',
    gradient: 'from-violet-600 to-fuchsia-600',
    accentColor: '#7c3aed',
    tags: ['lock-screen', 'phone', 'art'],
    isPremium: true,
  },
  {
    id: 'wallpaper-desktop',
    name: 'Desktop Wallpaper',
    category: 'wallpaper',
    width: 1920, height: 1080,
    description: '16:9 — PC & Mac desktop background',
    gradient: 'from-indigo-600 to-fuchsia-600',
    accentColor: '#4f46e5',
    tags: ['desktop', 'pc', 'mac'],
    isPremium: true,
  },

  // ── Festival ─────────────────────────────────────────────────────────────────
  {
    id: 'festival-diwali',
    name: 'Diwali Greetings',
    category: 'festival',
    width: 1080, height: 1080,
    description: '1:1 — Festival of lights celebration',
    gradient: 'from-orange-500 to-yellow-500',
    accentColor: '#f97316',
    tags: ['diwali', 'festival', 'lights', 'india'],
  },
  {
    id: 'festival-christmas',
    name: 'Christmas Card',
    category: 'festival',
    width: 1080, height: 1080,
    description: '1:1 — Festive Christmas greeting',
    gradient: 'from-red-600 to-green-600',
    accentColor: '#dc2626',
    tags: ['christmas', 'xmas', 'holiday'],
  },
  {
    id: 'festival-new-year',
    name: 'New Year',
    category: 'festival',
    width: 1080, height: 1080,
    description: '1:1 — Ring in the new year',
    gradient: 'from-indigo-500 to-yellow-400',
    accentColor: '#6366f1',
    tags: ['new-year', 'celebration', 'fireworks'],
  },
  {
    id: 'festival-eid',
    name: 'Eid Mubarak',
    category: 'festival',
    width: 1080, height: 1080,
    description: '1:1 — Eid ul-Fitr & Eid ul-Adha',
    gradient: 'from-emerald-600 to-teal-500',
    accentColor: '#059669',
    tags: ['eid', 'muslim', 'mubarak'],
  },
  {
    id: 'festival-birthday',
    name: 'Birthday Card',
    category: 'festival',
    width: 1080, height: 1080,
    description: '1:1 — Colorful birthday celebration',
    gradient: 'from-pink-500 to-violet-500',
    accentColor: '#ec4899',
    tags: ['birthday', 'celebration', 'party'],
  },
  {
    id: 'festival-holi',
    name: 'Happy Holi',
    category: 'festival',
    width: 1080, height: 1080,
    description: '1:1 — Festival of colors',
    gradient: 'from-pink-400 via-yellow-400 to-violet-500',
    accentColor: '#f472b6',
    tags: ['holi', 'colors', 'india', 'spring'],
  },
]

export const TEMPLATE_PACKS: TemplatePack[] = [
  {
    id: 'pack-social-starter',
    name: 'Social Starter Pack',
    description: 'Everything you need to launch your social media presence',
    gradient: 'from-pink-500 to-violet-600',
    emoji: '🚀',
    templateIds: ['instagram-square', 'instagram-story', 'instagram-portrait', 'youtube-thumbnail'],
  },
  {
    id: 'pack-business-pro',
    name: 'Business Pro Pack',
    description: 'Professional templates for brands and businesses',
    gradient: 'from-blue-600 to-indigo-600',
    emoji: '💼',
    templateIds: ['portrait-headshot', 'banner-linkedin', 'logo-modern', 'product-square'],
  },
  {
    id: 'pack-creator-kit',
    name: 'Creator Kit',
    description: 'YouTube thumbnails, shorts, and community posts',
    gradient: 'from-red-500 to-orange-500',
    emoji: '🎬',
    templateIds: ['youtube-thumbnail', 'youtube-gaming', 'youtube-shorts', 'youtube-tutorial'],
  },
  {
    id: 'pack-festival-bundle',
    name: 'Festival Bundle',
    description: 'All seasonal and festival greeting templates',
    gradient: 'from-orange-400 to-rose-500',
    emoji: '🎉',
    templateIds: ['festival-diwali', 'festival-christmas', 'festival-new-year', 'festival-eid', 'festival-birthday', 'festival-holi'],
  },
]
