/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as EditorIndexRouteImport } from './routes/editor/index'
import { Route as ToolsIndexRouteImport } from './routes/tools/index'
import { Route as ToolsToolIdRouteImport } from './routes/tools/$toolId'
import { Route as EditorProjectIdIndexRouteImport } from './routes/editor/$projectId/index'
import { Route as EditorProjectIdExportRouteImport } from './routes/editor/$projectId/export'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorIndexRoute = EditorIndexRouteImport.update({
  id: '/editor/',
  path: '/editor/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsToolIdRoute = ToolsToolIdRouteImport.update({
  id: '/tools/$toolId',
  path: '/tools/$toolId',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorProjectIdIndexRoute = EditorProjectIdIndexRouteImport.update({
  id: '/editor/$projectId/',
  path: '/editor/$projectId/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorProjectIdExportRoute = EditorProjectIdExportRouteImport.update({
  id: '/editor/$projectId/export',
  path: '/editor/$projectId/export',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/tools/$toolId': typeof ToolsToolIdRoute
  '/editor/': typeof EditorIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/editor/$projectId/export': typeof EditorProjectIdExportRoute
  '/editor/$projectId/': typeof EditorProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/tools/$toolId': typeof ToolsToolIdRoute
  '/editor': typeof EditorIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/editor/$projectId/export': typeof EditorProjectIdExportRoute
  '/editor/$projectId': typeof EditorProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/tools/$toolId': typeof ToolsToolIdRoute
  '/editor/': typeof EditorIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/editor/$projectId/export': typeof EditorProjectIdExportRoute
  '/editor/$projectId/': typeof EditorProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects'
    | '/tools/$toolId'
    | '/editor/'
    | '/tools/'
    | '/editor/$projectId/export'
    | '/editor/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects'
    | '/tools/$toolId'
    | '/editor'
    | '/tools'
    | '/editor/$projectId/export'
    | '/editor/$projectId'
  id:
    | '__root__'
    | '/'
    | '/projects'
    | '/tools/$toolId'
    | '/editor/'
    | '/tools/'
    | '/editor/$projectId/export'
    | '/editor/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsRoute: typeof ProjectsRoute
  ToolsToolIdRoute: typeof ToolsToolIdRoute
  EditorIndexRoute: typeof EditorIndexRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
  EditorProjectIdExportRoute: typeof EditorProjectIdExportRoute
  EditorProjectIdIndexRoute: typeof EditorProjectIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/': {
      id: '/editor/'
      path: '/editor'
      fullPath: '/editor/'
      preLoaderRoute: typeof EditorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/$toolId': {
      id: '/tools/$toolId'
      path: '/tools/$toolId'
      fullPath: '/tools/$toolId'
      preLoaderRoute: typeof ToolsToolIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/$projectId/': {
      id: '/editor/$projectId/'
      path: '/editor/$projectId'
      fullPath: '/editor/$projectId/'
      preLoaderRoute: typeof EditorProjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/$projectId/export': {
      id: '/editor/$projectId/export'
      path: '/editor/$projectId/export'
      fullPath: '/editor/$projectId/export'
      preLoaderRoute: typeof EditorProjectIdExportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsRoute: ProjectsRoute,
  ToolsToolIdRoute: ToolsToolIdRoute,
  EditorIndexRoute: EditorIndexRoute,
  ToolsIndexRoute: ToolsIndexRoute,
  EditorProjectIdExportRoute: EditorProjectIdExportRoute,
  EditorProjectIdIndexRoute: EditorProjectIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
